name: add_created_at
description: An appwrite cloud function, dart, which populates the createdAt field in a collection with the current time.

version: 1.0.0

environment:
  sdk: ">=2.7.0 <2.15.0"


dependencies:
  dart_appwrite: ^1.0.2
  http: ^0.13.3